version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - network
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
    - db-data:/var/lib/mysql
    - "./dev/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  db-data: {}
networks:
  network:
    driver: bridge