version: '3.6'
services:
  rent:
    image: rent:latest
    restart: always
    depends_on:
      - mysql:
          condition: service_healthy
    networks:
      - network
    ports:
      - 8080:8080
    env_file:
      - ./config.env
  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-data:/var/lib/mysql
      - "../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  db-data: {}
networks:
  network:
    driver: bridge